---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: arista
ansible_password: arista
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
# ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q juliopdx@192.168.33.61"'


custom_platform_settings:
  - platforms:
      - cEOS-lab
    management_interface: Management0

# Common AVD group variables
fabric_name: FABRIC

# Disable documentation generation
eos_designs_documentation:
  enable: false
eos_cli_config_gen_documentation:
  enable: false

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Local users
aaa_settings:
  local_users:
    # Username with no password configured
    - name: admin
      privilege: 15
      sha512_password: "$6$T4cuLcb/q.RtNIuR$H5LTfLpzLeKOv0dU7YILqQxy3G9AWnx0mILm22RumdvdUZ.Lj4PcXkP4V1aBy63Z7kggXLQAy2o4HrfpSYhSg0"
      no_password: true
    # Username with a password
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "$6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1."

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# Set default uplink, downlink, and MLAG interfaces based on node type
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3-4]
    downlink_interfaces: [Ethernet8]
  - types: [service_leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1]
    downlink_interfaces: [Ethernet8]
  - types: [l2leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]

# DNS Server
dns_settings:
  servers:
    - ip_address: 1.1.1.1

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 0.pool.ntp.org

mgmt_interface_vrf: default
