---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
      package_system: "python3.12"
      python_path: "/usr/bin/python3.12"
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: arista.avd
        version: 5.7.3

additional_build_steps:
    prepend_final:
        - RUN /usr/bin/dnf -y swap curl-minimal curl

options:
    package_manager_path: /usr/bin/dnf
