---
# Fabric Topology How-To Guide
# Spine configuration
type: spine

spine:
  defaults:
    platform: vEOS-lab # (1)!
    loopback_ipv4_pool: 10.255.0.0/27 # (2)!
    bgp_as: 65100 # (3)!

  nodes: # (4)!
    - name: htft-spine1
      id: 1 # (5)!
      mgmt_ip: 10.90.231.177/24 # (6)!
    - name: htft-spine2
      id: 2
      mgmt_ip: 10.90.231.178/24