---
# Fabric Topology How-To Guide
# Spine configuration
type: spine

spine:
  defaults:
    platform: cEOS-lab # (1)!
    loopback_ipv4_pool: 10.255.0.0/27 # (2)!
    bgp_as: 65100 # (3)!

  nodes: # (4)!
    - name: htft-spine1
      id: 1 # (5)!
      mgmt_ip: 172.16.2.11/24 # (6)!
    - name: htft-spine2
      id: 2
      mgmt_ip: 172.16.2.12/24