---
# validate.yml

- name: Test configuration
  hosts: htft-spine1
  gather_facts: false
  vars:
    avd_catalogs_enabled: false
    anta_runner_timeout: 15
    # user_catalogs_dir: "{{ anta_dir }}/{{ user_catalogs_dir_name }}/interfaces/"
  tasks:
    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.anta_runner
