---
# validate.yml

- name: Test configuration
  hosts: all
  gather_facts: false
  vars:
    # avd_catalogs_enabled: false
    anta_runner_timeout: 15
  tasks:
    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.anta_runner
