---
# validate.yml

- name: Test configuration
  hosts: htft-spine1
  gather_facts: false
  vars:
    avd_catalogs_enabled: false
  tasks:
    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.anta_runner
